<a href="https://colab.research.google.com/github/Oviya1710/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
## Multinested array

list1=[11,22,33,44,55]
list2=[10,20,30,40,50]
list3=[66,77,88,99,100]

arr1=np.array([list1,list2,list3])
arr1

array([[ 11,  22,  33,  44,  55],
       [ 10,  20,  30,  40,  50],
       [ 66,  77,  88,  99, 100]])

In [ ]:
arr1.shape      

(3, 5)

In [ ]:
arr1.reshape(5,3)      ## reshape,


array([[ 11,  22,  33],
       [ 44,  55,  10],
       [ 20,  30,  40],
       [ 50,  66,  77],
       [ 88,  99, 100]])

In [ ]:
## Indexing in 1D Array

arr=np.array([1,2,3,4,5,6,7,8,9])
arr[3]

4

In [ ]:
## Indexing in 2D Array
arr1[:,:]     #show all row,col

array([[ 11,  22,  33,  44,  55],
       [ 10,  20,  30,  40,  50],
       [ 66,  77,  88,  99, 100]])

In [ ]:
# fetch 11,22,10,20

arr1[0:2,0:2]

array([[11, 22],
       [10, 20]])

In [ ]:
# fetch 40,50,99,100

arr1[1:3,3:5]

array([[ 40,  50],
       [ 99, 100]])

In [ ]:
arr1=np.arange(0,10,step=2)
arr1

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
## copy function and broadcasting
arr1[3:]=500
arr1


array([  0,   2,   4, 500, 500])

In [ ]:
## some condition in EDA

val=2
arr1<2

array([ True, False, False, False, False])

In [ ]:
arr1[arr1<100]

array([0, 2, 4])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
## random distribution
np.random.rand(3,3)

array([[0.49436973, 0.32159301, 0.28565738],
       [0.22495702, 0.68802037, 0.93402559],
       [0.42168356, 0.6626565 , 0.55947641]])

In [ ]:
arr_ex=np.random.randn(4,4)

In [ ]:
arr_ex

array([[-1.16239193e+00, -7.62592974e-01, -5.92836362e-01,
         7.48651709e-01],
       [-4.39249233e-01, -9.66287935e-01, -1.66233227e+00,
        -6.78375248e-01],
       [ 5.39214665e-01,  1.31274577e+00, -1.03501446e+00,
        -1.31067062e+00],
       [ 8.28783346e-01, -4.47717119e-05,  2.76692954e+00,
        -1.18162677e+00]])

In [ ]:
np.random.randint(0,100,8).reshape(4,2)

array([[14, 85],
       [63, 18],
       [57, 59],
       [81,  9]])

In [ ]:
np.random.random_sample((1,5))

array([[0.05787776, 0.20188784, 0.7681539 , 0.92939326, 0.68480968]])